site_name: "Mathematical Modeling"
site_url: "https://jeubank2-x.github.io/mlb-modeling/"
site_dir: "docs"

theme:
  name: material

navbar:
  title: "MLB Statistical Modeling"
  right:
    - href: "https://jeubank2-x.github.io/"
      icon: fa-home
